// font-family: 'Merriweather', serif;
// font-family: 'Lora', serif;
// font-family: 'Open Sans Condensed', sans-serif;
// font-family: 'Droid Serif', serif;
// font-family: 'Playfair Display', serif;
// font-family: 'Josefin Sans', sans-serif;
// font-family: 'Titillium Web', sans-serif;
// font-family: 'Athiti', sans-serif;
// font-family: 'Noto Serif', serif;
// font-family: 'Dosis', sans-serif;
// font-family: 'Gurajada', serif;
// font-family: 'Aguafina Script', cursive;
// font-family: 'Share Tech', sans-serif;
// font-family: 'Artifika', serif;
// font-family: 'Text Me One', sans-serif;
// font-family: 'Rasa', serif;
// font-family: 'Condiment', cursive;
// font-family: 'Farsan', cursive;
// font-family: 'Lato', sans-serif;
// font-family: 'Abel', sans-serif;